name: Canary Build

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - build.sh

jobs:

  canary:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run build script
      run: |
        echo "::group::Ensure script is executable"
        chmod +x ./build.sh
        echo "::endgroup::"
        ./build.sh canary

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: canary-artifacts-$(date +'%Y-%m-%d-%H-%M-%S')
        path: hyprsource/artifact/
