name: Stable Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - build.sh
      - .github/workflows/stable.yaml

jobs:

  stable:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run build script
      run: |
        chmod +x ./build.sh
        ./build.sh stable

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: stable-artifacts
        path: ~/hyprsource/artifact/
